import Head from 'next/head'
import Navbar from '../components/navbar'
import HeroSection from '../components/heroSection';
import Style from "../styles/Home.module.css"
import Testimonial from '../components/testimonial';
import Service from '../components/services';
import About from '../components/about';







export default function Home() {
  return (
    <div className={Style.body}  >
      <div className="bg-white  dark:bg-gray-900 ">
        <Head>

          <title>Mehedi Official porfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />

        </Head>

        <header>
        </header>
          <Navbar></Navbar>
        <HeroSection></HeroSection>
        
        <main>
          <About></About>
          <Service></Service>
          <Testimonial></Testimonial>

        </main>


      </div>
    </div>
  )
}
