import Head from "next/head";
import Image from "next/image";
import React from "react";
import { useForm } from "react-hook-form";
import { RiSendPlaneFill } from "react-icons/ri";
import Layouts from "../../components/Layout/Layouts";
import Styles from ".././../styles/heroSection.module.css";

const Contacts = () => {
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm();
  const onSubmit = (data) => console.log(data);

  console.log(watch("example"));
  return (
    <div className="w-full flex justify-center items-baseline  backdrop-blur-2xl">
      <Head>
        <title>Mehedi Offcial | Showcase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="  backdrop-blur-2xl">
        <div className="flex items-center    ">
          <div className="w-full flex justify-center">
            <Image
              class={`orderfirst swanAnimantion ${Styles.swanAnimantion}`}
              sizes="(max-width: 768px) 100vw, 33vw"
              width={500}
              height={500}
              alt="contact-us"
              src="/Contact_us.png"></Image>
          </div>
          <div className="w-full ">
          <div className="p-4 box-border shadow-md border">

          <h1 className="text-4xl  font-semibold mb-2 text-blue-800">
              Send us <span className="text-green-400">messsage</span>
            </h1>
            <form onSubmit={handleSubmit(onSubmit)}>
              {/* register your input into the hook by invoking the "register" function */}
              <input
                placeholder="Enter your name"
                className="w-full block border-2 p-2 rounded mb-2"
                {...register("Name", { required: true })}
              />

              {/* include validation with required or other standard HTML validation rules */}
              <input
                type="email"
                placeholder="Enter your valid email adress"
                className=" w-full p-2 border-2  rounded mb-2"
                {...register("email", { required: true })}
              />
              <textarea
                type=""
                placeholder="Enter your message here"
                className="w-full py-4 border-2"
                {...register("message", { required: true })}
              />
              {/* errors will return when field validation fails  */}
              {(errors.name || errors.email || errors.message) && (
                <p className="text-red-400">This field is required</p>
              )}

              <button type="submit" className=" p-2 border  border-gray-400 rounded dark:text-white ">
                Send  🚀{/* <RiSendPlaneFill className="ml-1 "></RiSendPlaneFill> */}
              </button>
            </form>
          </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Contacts;

Contacts.getLayout = function getLayout(page) {
  return <Layouts>{page}</Layouts>;
};
