import Head from "next/head";
import React from "react";

const Contacts = () => {
  return (
    <div className="flex justify-center align-middle  h-screen items-center">
      <Head>
        <title>Mehedi Offcial | Showcase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Contacts form are cooming soon...</h1>
    </div>
  );
};

export default Contacts;
