import Head from "next/head";
import React from "react";
import Layouts from "../../components/Layout/Layouts";
import Card from "../../components/ui/card";

const ShowCase = () => {
  const dummy = [1, 2, 3, 4];
const porjects =[{
  name:"Pc-builder site",
  imageUrl:"https://i.ibb.co/5FR2kF4/pcbuilder.png",
  github:"https://github.com/mehedi494/Pc-builder",
  liveLink:"https://pc-builder-fronend.vercel.app/",
  tools:" react.js Express.js, MongoDB"
},
{
  name:"BookSellig site",
  imageUrl:"https://i.ibb.co/Fg2cBY9/book-Shelf.png",
  github:"https://github.com/mehedi494/book-shelf",
  liveLink:"https://book-self-frontend.onrender.com/",
  tools:" Next.js Express.js, MongoDB"
},
{
  name:"Dental Service Site",
  imageUrl:"https://i.ibb.co/gSTr61M/doctor-portal.png  ",
  github:"https://github.com/mehedi494/Doctors_PortalClient",
  liveLink:"https://sparkling-beijinho-ad8483.netlify.app/",
  tools:"React.js, Firebase, Express.js, MongoDB"
}
]

  return (
    <div className="flex justify-center align-middle  items-center">
      <Head>
        <title>Mehedi Offcial | Showcase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <div className="grid grid-cols-3 my-2 gap-4">
        {porjects.map((item, index) => (
          <Card
            key={index}
            /* srcUrl="/man1.jpg" */
            srcUrl={item.imageUrl}
            cartTitle={item.name}
            cardBody={item.tools}
            github={item.github}
            liveLink={item.liveLink}
            buttonTitle1="Live-link"
            buttonTitle2="source-code"></Card>
        ))}
      </div>
    </div>
  );
};

export default ShowCase;

ShowCase.getLayout = (page) => {
  return <Layouts>{page}</Layouts>;
};
