import Head from "next/head";
import React from "react";
import Layouts from "../../components/Layout/Layouts";
import Card from "../../components/ui/card";

const ShowCase = () => {
  const dummy = [1, 2, 3, 4];
  return (
    <div className="flex justify-center align-middle  items-center">
      <Head>
        <title>Mehedi Offcial | Showcase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*  <div className="grid grid-cols-3 gap-4">
        {dummy.map((item,index ) => (
            <Card
              key={index}
              srcUrl="/Dark-blu-bg.jpg"
              cardTitle="Demo Card"
              cardBody="This is a demo card"
              buttonTitle="View More"
            />
          )
        )}
      </div> */}

      <div className="grid grid-cols-3 gap-4">
        {dummy.map((item, index) => (
          <Card
            key={index}
            /* srcUrl="/man1.jpg" */
            srcUrl="https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&q=80&w=1469&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
            cartTitle="This demo card"
            cardBody="This Card body"
            github={`http://github.com/mehedi494/`}
            liveLink={`http://github.com/mehedi494/`}
            buttonTitle1="Live-link"
            buttonTitle2="source-code"></Card>
        ))}
      </div>
    </div>
  );
};

export default ShowCase;

ShowCase.getLayout = (page) => {
  return <Layouts>{page}</Layouts>;
};
