import Head from "next/head";
import React from "react";
import Card from "../../components/ui/card";

const ShowCase = () => {
  const dummy = [1, 2, 3, 4];
  return (
    <div className="flex justify-center align-middle  items-center">
      <Head>
        <title>Mehedi Offcial | Showcase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*  <div className="grid grid-cols-3 gap-4">
        {dummy.map((item,index ) => (
            <Card
              key={index}
              srcUrl="/Dark-blu-bg.jpg"
              cardTitle="Demo Card"
              cardBody="This is a demo card"
              buttonTitle="View More"
            />
          )
        )}
      </div> */}

      <div className="grid grid-cols-3 gap-4">
        {dummy.map((item, index) => (
          <Card
            key={index}
            srcUrl="/Dark-blu-bg.jpg"
            cartTitle="This demo card"
            cardBody="This Card body"
            buttonTitle="view more"></Card>
        ))}
      </div>
    </div>
  );
};

export default ShowCase;
<h1>Project are comming soon...</h1>;
